"use strict";

module.exports = {
  beRules: require("./be-rules"),
  codegen: require("./codegen"),
  collaboration: require("./collaboration"),
  commitPolicy: require("./commit-policy"),
  configDoctor: require("./config-doctor"),
  configFix: require("./config-fix"),
  permissionExport: require("./permission-export"),
  configInit: require("./config-init"),
  configLayering: require("./config-layering"),
  configProbe: require("./config-probe"),
  contract: require("./contract"),
  contractCompat: require("./contract-compat"),
  deterministic: require("./deterministic"),
  doctor: require("./doctor"),
  envMatrix: require("./env-matrix"),
  installer: require("./installer"),
  impactAnalysis: require("./impact-analysis"),
  integrationContract: require("./integration-contract"),
  manifest: require("./manifest"),
  projectCatalog: require("./project-catalog"),
  reporters: require("./reporters"),
  safeFix: require("./safe-fix"),
  taskRouter: require("./task-router"),
  pipeline: require("./pipeline"),
  contextPlanner: require("./context-planner"),
  templateEngine: require("./template-engine"),
  troubleshoot: require("./troubleshoot"),
};
